Repository modern-agile-team/create-dev-portfolio, pull requests merged in 2022-10, with the labels that each got.

#2 [Feature/kjs/#1] Application action script
  package.json
  scripts/start-all.sh
  scripts/stop-server.sh
Labels: enhancement

#14 [Docs] Add DB ERD to README.md file
  README.md
Labels: documentation

#17 Update localhost to each deployed host address, and then Change the host address string to ENVIRONMENT_VARIABLE.
  README.md
  client/app/src/apis/instance.ts
  config/.client.env
  config/.server.env
  server/.db/etc/my.cnf
  server/app/src/config/db.ts
  server/dockerfile
Labels: bug

#20 docs: update README.md
  README.md
  client/README.md
  server/README.md
Labels: documentation

#35 Add typdoc in server's source code
  server/app/src/apis/middlewares/validationCheck.ts
  server/app/src/apis/module/error.ts
  server/app/src/apis/visitor/visitor.ctrl.ts
  server/app/src/apis/visitor/visitor.d.ts
  server/app/src/model/visitorRepository.ts
  server/app/src/service/visitor.ts
Labels: documentation

#39 build: Update depandencies of package*.json
  README.md
  client/app/package-lock.json
  client/app/package.json
  package-lock.json
  server/app/package-lock.json
Labels: documentation, build
